# Configuration for options strategy simulation

simulation:
  type: options_strategy
  paths: 1000
  horizon: 40  # Trading days until option expiration

stock:
  ticker: IBIT
  model: gbm
  starting_price: auto

# Common parameters shared by all models
model_params:
  volatility: auto
  drift: auto
  random_seed: 42

# Model-specific parameters
models:
  gbm:  # Geometric Brownian Motion parameters
    # These override any common parameters defined above
    mean_reversion: 0.0  # GBM doesn't use this, just demonstrating structure
  
  heston:  # Heston stochastic volatility model parameters
    mean_reversion: 0.05
    volatility_volatility: 0.3
    correlation: -0.7
    long_run_variance: 0.04
  
  jump_diffusion:  # Jump diffusion model parameters
    jump_intensity: 0.1
    jump_mean: -0.05
    jump_std: 0.1

strategy:
  - action: BUY
    instrument: STOCK
    quantity: 100
  - action: SELL
    instrument: CALL
    quantity: 100
    strike: 10%OTM  # 10% Out of the Money
    expiration: 30d  # 90 days

options:
  pricing_model: black_scholes  # Options pricing model (black_scholes, binomial, heston)

data:
  lookback_period: "1y"  # Changed from 252 to "1y" string format
  frequency: daily
  risk_free_rate: auto  # Fetch current risk-free rate
  dividend_yield: 0.0   # Dividend yield if applicable
  # Cache control settings
  cache:
    enabled: true
    max_age: 86400
    force_refresh: false

visualization:
  plot_paths: true               # Plot strategy value paths
  plot_payoff: true              # Plot payoff diagram at expiration
  plot_strategy_vs_stock: true   # Compare strategy returns against stock-only returns
  plot_distribution: true        # Plot distribution of final values
  confidence_intervals: [0.1, 0.5, 0.9]
  output_dir: outputs            # Directory to save output images
  save_to: outputs/tsla_covered_call.png