# Default configuration for stock simulation

simulation:
  type: stock
  ticker: AAPL
  model: gbm
  paths: 10  # Reduced from 1000 for better performance
  horizon: 30  # Trading days (1 year)
  starting_price: auto  # Fetch from market data

model_params:
  volatility: auto  # Calculate from historical data
  drift: auto       # Calculate from historical data
  random_seed: 42

data:
  lookback_period: "1y"  # Changed from 252 to "1y" string format
  frequency: daily

visualization:
  plot_paths: true
  confidence_intervals: [0.1, 0.5, 0.9]
  save_to: outputs/aapl_sim.png