# Default configuration for stock simulation

simulation:
  type: stock
  ticker: GOOG
  model: gbm
  paths: 250  # Reduced from 1000 for better performance
  horizon: 30  # Trading days 30 days
  starting_price: auto  # Fetch from market data

model_params:
  volatility: auto  # Calculate from historical data
  drift: auto       # Calculate from historical data
  random_seed: 42

data:
  lookback_period: "1y"  # Changed from 252 to "1y" string format
  frequency: daily
  # Cache control settings
  cache:
    enabled: true        # Enable/disable data caching
    max_age: 86400       # Maximum age of cached data in seconds (24 hours)
    force_refresh: false # Force refresh of data even if cached

visualization:
  plot_paths: true
  confidence_intervals: [0.1, 0.5, 0.9]
  save_to: outputs/goog_sim.png